### ISSUE TITLE
cannot convert `var`

### ISSUE THREAD

**Issue by e-cloud** [lebab/lebab#205]
First:
I try to convert some file with var declaration.
got error stacktrace:
```js
/home/cloud/devlab/refactor-tool/node_modules/lebab/lib/Logger.js:33
        line: node.loc.start.line,
                      ^

TypeError: Cannot read property 'start' of undefined
    at Logger.warn (/home/cloud/devlab/refactor-tool/node_modules/lebab/lib/Logger.js:33:23)
    at logWarningForVarKind (/home/cloud/devlab/refactor-tool/node_modules/lebab/lib/transform/let.js:204:12)
    at /home/cloud/devlab/refactor-tool/node_modules/lebab/lib/transform/let.js:176:7
    at Array.forEach (native)
    at transformVarsToLetOrConst (/home/cloud/devlab/refactor-tool/node_modules/lebab/lib/transform/let.js:164:31)
    at leaveFunction (/home/cloud/devlab/refactor-tool/node_modules/lebab/lib/transform/let.js:158:3)
    at Controller.leave (/home/cloud/devlab/refactor-tool/node_modules/lebab/lib/transform/let.js:48:9)
    at Controller.__execute (/home/cloud/devlab/refactor-tool/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/cloud/devlab/refactor-tool/node_modules/estraverse/estraverse.js:491:28)
    at Object.traverse (/home/cloud/devlab/refactor-tool/node_modules/estraverse/estraverse.js:713:27)
```

It turns out [`VariableDeclaration`](https://github.com/lebab/lebab/blob/20e3925cc87d6863c7d0cf912f724d6f53d583d7/src/syntax/VariableDeclaration.js#L14) doesn't have loc property. But the `Logger` [try to log the location](https://github.com/lebab/lebab/blob/master/src/transform/let.js#L152)

**Comment by nene** [comment]
I somewhat imagine what could be causing this, but could you provide some example code that causes this and name the transform that you're using. My first attempt of reproducing this didn't succeed.

**Comment by nene** [comment]
Turns out that the problem is caused by using `multi-var` and `let` transforms together - and in that particular order. Can be reproduced with the following code:

```js
foo++;
var foo = 1, bar = 2;
```

The problem is that these transforms modify the same things and as a result step on each others toes. `multi-var` creates new VariableDeclaration nodes for which it doesn't give any location information and `let` transform is unable to transform one of these declarations, so it wants to print out error for which it wants to use the location information.

- First off I have to say that applying lots of transforms in one go is a recipe for running into all kinds of problems. Lebab README warns you against that. You really should expect what each transform does, not apply them blindly.
- A temporary fix for this in Lebab could be to ignore the missing line number information when printing out errors.
- A proper fix would be to ensure we always add line number information when creating new nodes. There are lots of places where we create new nodes, so it's not so easily solvable.

Thanks for the bug report.

**Comment by Viatorus** [comment]
Any news on this bug?

**Comment by nene** [comment]
Not a priority. Pull requests always welcome of course.

28.05.2017 8:10 AM kirjutas kuupäeval "Viatorus" <notifications@github.com>:
