### ISSUE TITLE
Error with export <ident> from syntax

### ISSUE THREAD

**Issue by wKich** [lebab/lebab#207]
If I want to apply some transformation to my source code files that contain syntax from proposal stages, I get exception for that files.

For example:
I want to replace `commonjs` syntax in some my files, but I also have files with export-from statements
```js
// src/foo.js
module.exports = 'foo'

// src/index.js
export foo from './foo'
```
When a run `lebab --replace src -t commonjs` I get this exception
```js
/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:412
        throw err;
        ^

SyntaxError: Unexpected token foo
    at Parser.instance.raise.instance.raiseRecoverable (/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:408:19)
    at Parser.instance.unexpected (/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:441:14)
    at Parser.pp.expect (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:610:26)
    at Parser.pp$1.parseExportSpecifiers (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:1329:8)
    at Parser.pp$1.parseExport (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:1260:28)
    at Parser.pp$1.parseStatement (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:754:69)
    at Parser.pp$1.parseTopLevel (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:658:23)
    at Parser.parseTopLevel (/usr/local/lib/node_modules/lebab/node_modules/espree/espree.js:270:34)
    at Parser.parse (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:528:15)
    at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/acorn/dist/acorn.js:3357:37)
```

**Comment by nene** [comment]
Seems to be a bug in [espree](https://github.com/eslint/espree) parser:

- http://astexplorer.net/#/HcsXwyydjG

I'm currently working on switching over to Babylon parser. If that succeeds, it'll fix this issue.

**Comment by nene** [comment]
Filed bug report to espree as well: https://github.com/eslint/espree/issues/312

**Comment by wKich** [comment]
It's not bug in espree, because the `export foo from './foo'` is in stage 1 proposal [https://github.com/leebyron/ecmascript-export-default-from](url).

But yeah, switching to Babylon fix this issue.

**Comment by nene** [comment]
Yep, just realized this by myself.

Currently Lebab doesn't really support much else besides ES2016.

Hopefully there will be support for this and new syntax by adopting Babylon. But the lack of this feature in itself is currently not a bug.
