### ISSUE TITLE
lebab es5.js -o es6.js --transform let; espree.js:461 throw err

### ISSUE THREAD

**Issue by tibic** [lebab/lebab#252]
\node_modules\lebab\node_modules\espree\espree.js:461
        throw err;

**Comment by nene** [comment]
Thanks for the bug report. Seems to be a parsing error. Please be more specific though.

- What's in the input es5.js file that you're giving to Lebab?
- Are you running the latest version of Lebab? Did it work in earlier version?

**Comment by thomasjm** [comment]
I'm seeing this too, when trying to convert Typescript files. I guess this tool doesn't support Typescript? In a codebase of about 100 files, only about 10 converted while the rest had this parsing error.

**Comment by nene** [comment]
@thomasjm Yep. No TypeScript support as the parsers used by Lebab don't support it either.

Closing this issue given no further feedback from @tibic

**Comment by MV88** [comment]
Hi, not sure if i'm late but in this project after installing its dependencies and lebab globally i have this problem:

`lebab --replace web/client/components/app/StandardApp.jsx --transform commonjs`

```
$ lebab --replace 'web/client/components/app/*.jsx' --transform commonjs
C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\espree\lib\espree.js:219
        throw err;
        ^

SyntaxError: Unexpected token =
    at Espree.raise (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\espree\lib\espree.js:214:21)
    at Espree.unexpected (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\espree\lib\espree.js:259:14)
    at Espree.pp.expect (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:683:28)
    at Espree.pp$3.parseMethod (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:2609:10)
    at Espree.pp$1.parseClassMethod (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:1387:25)
    at Espree.pp$1.parseClassElement (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:1376:10)
    at Espree.pp$1.parseClass (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:1315:26)
    at Espree.pp$1.parseStatement (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:833:19)
    at Espree.pp$1.parseTopLevel (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\acorn\dist\acorn.js:746:23)
    at Espree.parseTopLevel (C:\Users\geosolutions\AppData\Roaming\npm\node_modules\lebab\node_modules\espree\lib\espree.js:202:22) {
  index: 2171,
  lineNumber: 51,
  column: 22
}
```

**Comment by nene** [comment]
Hmm.. I guess it's indeed the case that Lebab doesn't report filename when crashing.

But as I understand, you know where the error is:

```
web/client/components/app/StandardApp.jsx
lineNumber: 51,
column: 22
```

And as I understand you have the same problem of using the `static` keyword in all other files. So you're somewhat out of luck with Lebab not supporting this.

**Comment by MV88** [comment]
ah I see now,
so basically all our class-like components are not parsable because of the 
static propTypes or static defaultProps but event public instance fields are not supported as reported by you [here](https://github.com/lebab/lebab/issues/237#issuecomment-296970385).

So, is there an automagic way to migrate react components like them to es6 syntax?

Really thanks for the quick reply

**Comment by nene** [comment]
Actually there are two babel plugins for specifically these import/export transforms:

- https://github.com/rajatvijay/lebab-as-babel-plugins

Maybe you can make them work for you.

**Comment by MV88** [comment]
Hi, i just wanted to porst my solution also for others. 
I was able to achieve what i wanted with [5to6-codemod](https://github.com/5to6/5to6-codemod) and with [jscodeshift](https://github.com/facebook/jscodeshift)

I used this command
`jscodeshift -t node_modules/5to6-codemod/transforms/cjs.js rootFolder/ --extensions=jsx,js`
regarding module.exports = i just used atom's find/replace functionality

The only problem is that i wasn't able to convert also inline require, but they are not too much file and I can handle them manually
