### ISSUE TITLE
Class transformation fails when trying to transform anonymous function 

### ISSUE THREAD

**Issue by inondle** [lebab/lebab#305]
I'm transforming a few legacy js files with my own code mods in addition to lebab. One file looks like this after a few codemods:

```
export default function (id) {
        function functionA(opts) {
            // ...
        };

        function functionB(opts) {
            // ...
        };

        return {
            functionA: functionA,
            functionB: functionB
        }
    };
```

When lebab tries to apply the class transformation to it, it fails with this stacktrace: 
```
C:\source\repos\test\node_modules\lebab\lib\transform\class\matchFunctionDeclaration.js:10
      className: node.id.name,
                         ^

TypeError: Cannot read property 'name' of null
    at exports.default (C:\source\repos\test\node_modules\?[4mlebab?[24m\lib\transform\class\matchFunctionDeclaration.js:10:26)
    at Controller.enter (C:\source\repos\test\node_modules\?[4mlebab?[24m\lib\transform\class\index.js:15:54)
    at Controller.__execute (C:\source\repos\test\node_modules\?[4mestraverse?[24m\estraverse.js:330:31)
    at Controller.traverse (C:\source\repos\test\node_modules\?[4mestraverse?[24m\estraverse.js:434:28)
    at Object.traverse (C:\source\repos\test\node_modules\?[4mestraverse?[24m\estraverse.js:646:27)
    at Object.traverse (C:\source\repos\test\node_modules\?[4mlebab?[24m\lib\traverser.js:54:33)
    at exports.default (C:\source\repos\test\node_modules\?[4mlebab?[24m\lib\transform\class\index.js:11:23)
    at C:\source\repos\test\node_modules\?[4mlebab?[24m\lib\Transformer.js:69:11
    at Array.forEach (<anonymous>)
    at C:\source\repos\test\node_modules\?[4mlebab?[24m\lib\Transformer.js:68:26
```

Seems like the problem here is that it's trying to get the name of the anonymous function and it fails since `node.id` is null.

**Comment by inondle** [comment]
Closing, wasn't on latest version. Updating to version 3.1.0 fixes this.
