### ISSUE TITLE
catch {} not recognized

### ISSUE THREAD

**Issue by dilyanpalauzov** [lebab/lebab#318]
With this file a.js
```javascript
'use strict';

function a() {
    try {
        console.log('A');
    } catch {
        console.log('B');
    }
}
```

`lebab --replace a.js --transform no-strict` fails with

```
node_modules/.bin/lebab --replace src/js/common/datetime.js --transform no-strict
node_modules/espree/lib/espree.js:195
            throw err;
            ^

SyntaxError: Unexpected token {
    at Espree.raise (/git/bapha/node_modules/espree/lib/espree.js:190:25)
    at Espree.unexpected (/git/bapha/node_modules/espree/lib/espree.js:235:18)
    at Espree.pp$1.parseTryStatement (/git/bapha/node_modules/acorn/dist/acorn.js:1085:51)
    at Espree.pp$1.parseStatement (/git/bapha/node_modules/acorn/dist/acorn.js:847:34)
    at Espree.pp$1.parseBlock (/git/bapha/node_modules/acorn/dist/acorn.js:1170:23)
    at Espree.pp$3.parseFunctionBody (/git/bapha/node_modules/acorn/dist/acorn.js:2777:24)
    at Espree.pp$3.parseMethod (/git/bapha/node_modules/acorn/dist/acorn.js:2716:10)
    at Espree.pp$3.parsePropertyValue (/git/bapha/node_modules/acorn/dist/acorn.js:2636:25)
    at Espree.pp$3.parseProperty (/git/bapha/node_modules/acorn/dist/acorn.js:2621:10)
    at Espree.pp$3.parseObj (/git/bapha/node_modules/acorn/dist/acorn.js:2567:23) {
  index: 2031,
  lineNumber: 74,
  column: 17
}
error Command failed with exit code 1.
```

**Comment by dilyanpalauzov** [comment]
Moved to https://github.com/lebab/lebab/issues/318.
