### ISSUE TITLE
`recast` with `espree` failed on `new.target`

### ISSUE THREAD

**Issue by pionxzh** [lebab/lebab#352]
I know this might look like I'm reporting in the wrong place. Let me explain.

1. `espree` can parse the code without error
2. `recast` with `espree` will have this error
3. `recast` with default parser (`esprima`) will *not* have this error
4. `recast` does not officially support `espree` as parser, that why I report it here

I don't know which project should be responsible for this. 

I have tried various `espree` options to make it work. But failed.

### Input

```js
const { transform } = require('lebab');
const code = `function foo() { new.target }`;

transform(
    code, // code to transform
    ['let'] // transforms to apply
);
```

### Output

```
TypeError: Cannot read properties of undefined (reading 'line')
    at Object.fixFaultyLocations (\node_modules\recast\lib\util.js:153:23)
    at TCp.copy (\node_modules\recast\lib\parser.js:138:10)
    at TCp.copy (\node_modules\recast\lib\parser.js:190:30)
    at TCp.copy (\node_modules\recast\lib\parser.js:190:30)
    at TreeCopier.<anonymous> (\node_modules\recast\lib\parser.js:131:30)
    at Array.forEach (<anonymous>)
    at TCp.copy (\node_modules\recast\lib\parser.js:130:14)
    at TCp.copy (\node_modules\recast\lib\parser.js:190:30)
    at TCp.copy (\node_modules\recast\lib\parser.js:190:30)
    at TreeCopier.<anonymous> (\node_modules\recast\lib\parser.js:131:30)
```

The wrong node is the `new.target` (MetaProperty)

```json
{
  "type": "Identifier",
  "start": 20,
  "end": 23,
  "loc": {
    "end": {
      "line": 2,
      "column": 5
    }
  },
  "name": "new"
}
```

**Comment by pionxzh** [comment]
`new.target` is `MetaProperty` in the AST node. The expectation is not to throw an error when `lebab` processes this code snippet. `lebab` won't transform this code, but the tool (`recast` + `espree`) combination will fail on this.

Or maybe we can have an option to customize the parser used by `recast`? I tried the default parser(esprima) can works normally.

**Comment by nene** [comment]
Well... I'll need to take a closer look when I get back.

Possibly Lebab could switch to a different parser. I don't really remember why exactly it uses espree. There likely were some issues with other parsers. But it's been a while and sure these parsers have advanced a bit. Lebab isn't really in active development. It's not really even in active maintenance. But when I feel like it, I might fix a bug or two. Though switching a parser is probably a fairly involved task.

**Comment by pionxzh** [comment]
I can understand the status of this project. Don't worry 🙏 
I can send a PR for the parser part.

**Comment by nene** [comment]
Sure. I'm open for a PR.

**Comment by pionxzh** [comment]
This issue seems fixed for me... I'm not sure why 💦

**Comment by nene** [comment]
So, I finally started looking closer at this issue, and I'm unable to reproduce it.

Testing with this snippet:

```js
function foo() { new.target }
```

It works just fine on my machine, and when I try it in the [demo site](https://lebab.github.io/), it also works without problems.

I see you [patched the problem in Recast](https://github.com/pionxzh/wakaru/commit/c57c69ae4349ceef1b425d78769c50bf7cb00072). I suggest you send that patch to Recast repository. I'm sure Recast also wants to support the Espree parser (although it doesn't explicitly list a configuration for it in its `parsers/` dir).

But I guess the important bit is making this bug first reproducible. Currently for me it's not.

**Comment by pionxzh** [comment]
Run this in Node.js. Not sure why web is fine.
```js
const { transform } = require('lebab')

const code = `function foo() { new.target }`;

transform(
  code, // code to transform
  ['let'] // transforms to apply
);
```

**Comment by pionxzh** [comment]
```js
var espree = require('espree')
var recast = require('recast')

const code = `
function foo() { new.target }
`

const ESPREE_OPTS = {
  ecmaVersion: 2022,
  ecmaFeatures: {jsx: true},
  comment: true,
  tokens: true,
  range: true,
  loc: true,
};

var parser = {
  parse: function parse(js, opts) {
    return espree.parse(js, ESPREE_OPTS);
  }
};

const ast = recast.parse(code, { parser })

const result = recast.print(ast, {
  lineTerminator: '\n',
  objectCurlySpacing: false,
}).code;

console.log(result);
```

**Comment by nene** [comment]
> Run this in Node.js. Not sure why web is fine.

Tried. Works without issues.

**Comment by nene** [comment]
This other example also works without issue for me.

**Comment by nene** [comment]
Also running in [codesandbox.io](https://codesandbox.io/p/devbox/zen-carson-d7p9ns?file=%2Fsrc%2Findex.js%3A9%2C1)

**Comment by pionxzh** [comment]
Hmm. What OS did you use?

**Comment by pionxzh** [comment]
It works fine on my Mac. WTF.

**Comment by nene** [comment]
Yeah, I'm using Mac. Node 18.

**Comment by nene** [comment]
Perhaps there's something off with your windows environment. Maybe you can ask somebody to try it on Windows. I currently don't have a Windows at hand.

**Comment by nene** [comment]
I'd suspect it's a difference in Node environment, not a difference in OS.
